// src/types/client.ts
import type { Timestamp } from "firebase/firestore";

// Interface for data coming from Firestore (includes id)
export interface Client {
  id: string;
  name: string;
  logoUrl: string;
  editorialLine: string;
  budget: number;
  services: string[];
  credentials?: string;
  metaIntegration?: {
    adAccountId: string;
    accessToken: string;
  };
}

// Interface for creating a new client (id is generated by Firestore)
export type NewClient = Omit<Client, 'id' | 'metaIntegration'> & {
    metaAdsAccountId?: string; // Kept for backwards compatibility on creation if needed
};
