// src/types/client.ts

// Interface for data coming from Firestore (includes id)
export interface Client {
  id: string;
  name: string;
  logoUrl: string;
  editorialLine: string;
  budget: number;
  services: string[];
  credentials?: string;
  metaAdsAccountId?: string;
}

// Interface for creating a new client (id is generated by Firestore)
export type NewClient = Omit<Client, 'id'>;
