// src/types/client.ts
import type { Timestamp } from "firebase/firestore";

// Interface for data coming from Firestore (includes id)
export interface Client {
  id: string;
  name: string;
  logoUrl: string;
  editorialLine: string;
  budget: number;
  services: string[];
  credentials?: string;
  metaAdsAccountId?: string; // Legacy or simple field
  metaIntegration?: {
    adAccountId: string;
    userAccessToken: string; // Encrypted access token
    tokenExpiresAt: Timestamp;
  };
}

// Interface for creating a new client (id is generated by Firestore)
export type NewClient = Omit<Client, 'id'>;
